[project]
name = "timeweb-sdk"
version = "0.1.0.dev0"
description = "Python SDK for Timeweb Cloud API"
authors = [
    {name = "vlaszdunov",email = "zdunovvl@gmail.com"}
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages=[{include="timeweb_sdk",from="src"}]
requires-poetry = ">=2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
