name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get-version.outputs.version }}
      wheel_path: ${{ steps.collect-dist.outputs.wheel }}
      sdist_path: ${{ steps.collect-dist.outputs.sdist }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: '3.13'

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run pytest --junit-xml=./test-results.xml

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          fail-on-empty: true
          title: Test results

      - name: Get package version
        id: get-version
        run: echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Build package
        run: poetry build

      - name: Collect dist paths
        id: collect-dist
        run: |
          wheel=$(echo dist/*.whl)
          sdist=$(echo dist/*.tar.gz)
          echo "wheel=$wheel" >> "$GITHUB_OUTPUT"
          echo "sdist=$sdist" >> "$GITHUB_OUTPUT"

      - name: Cleanup dist/
        run: rm -rf dist/

  upload-artifacts:
    needs: run-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [ wheel, sdist ]

    steps:
      - name: Upload ${{ matrix.type }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}-${{ needs.run-tests.outputs.version }}
          path: ${{ matrix.type == 'wheel' && needs.run-tests.outputs.wheel_path || needs.run-tests.outputs.sdist_path }}
