name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: '3.13'

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run pytest --junit-xml=./test-results.xml

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          fail-on-empty: true
          title: Test results

      - name: Get package version
        id: get-version
        run: echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Build package
        run: poetry build

      - name: Upload dist/ for later jobs
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  upload-artifacts:
    needs: run-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [wheel, sdist]

    steps:
      - name: Download built dist/
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Upload ${{ matrix.type }} with version
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}-${{ needs.run-tests.outputs.version }}
          path: |
            ${{ matrix.type == 'wheel' && 'dist/*.whl' || 'dist/*.tar.gz' }}
