name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run pytest --junit-xml=./test-results.xml

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          fail-on-empty: true
          title: Test results

      - name: build
        run: poetry build

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/