name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run pytest --junit-xml=./test-results.xml

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          # A list of JUnit XML files, directories containing the former, and wildcard
          # patterns to process.
          # See @actions/glob for supported patterns.
          path: test-results.xml

          # (Optional) Add a summary of the results at the top of the report
          summary: true

          # (Optional) Fail the workflow if no JUnit XML was found.
          fail-on-empty: true

          # (Optional) Title of the test results section in the workflow summary
          title: Test results